language: elixir
elixir:
  - 1.10
  - 1.9
  - 1.8
  - 1.7
otp_release:
  - 22.2
  - 22.1
  - 21.3
matrix:
  exclude:
    - elixir: 1.7
      otp_release: 22.2
    - elixir: 1.7
      otp_release: 22.1
services:
  - redis-server
script:
  - mix test
notifications:
  email:
    on_success: never
    on_failure: never
