language: elixir
elixir:
  - 1.6
  - 1.5
  - 1.4
otp_release:
  - 20.3
  - 20.2
  - 20.1
  - 20.0
  - 19.2
services:
  - redis-server
script:
  - mix test
notifications:
  email:
    on_success: never
    on_failure: never
