language: elixir
elixir:
  - 1.9
  - 1.8
  - 1.7
  - 1.6
otp_release:
  - 22.0
  - 21.3
  - 21.2
  - 20.3
matrix:
  exclude:
    - elixir: 1.9
      otp_release: 20.3
    - elixir: 1.8
      otp_release: 20.3
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.6
      otp_release: 21.3
    - elixir: 1.6
      otp_release: 21.2
services:
  - redis-server
script:
  - mix test
notifications:
  email:
    on_success: never
    on_failure: never
