language: elixir
elixir:
  - 1.7
  - 1.6
otp_release:
  - 21.1
  - 21.0
  - 20.3
  - 20.2
  - 20.1
matrix:
  exclude:
    - elixir: 1.7
      otp_release: 20.3
    - elixir: 1.7
      otp_release: 20.2
    - elixir: 1.7
      otp_release: 20.1
    - elixir: 1.6
      otp_release: 21.1
    - elixir: 1.6
      otp_release: 21.0
services:
  - redis-server
script:
  - mix test
notifications:
  email:
    on_success: never
    on_failure: never
